# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: ["main"]

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: prereqs
        run: |
          sudo apt-get -y update
          sudo apt-get install -y \
            git-core \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            gfortran \
            libblas-dev \
            liblapack-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Render CV
        run: Rscript -e 'rmarkdown::render("long_form_cv/long_form_cv_vitae.Rmd")'
      - name: Render resume
        run: Rscript -e 'rmarkdown::render("one_page_resume/one_page_resume_pagedown.Rmd")'
      
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Update github.io site and commit results
        run: |
          cp one_page_resume/one_page_resume_pagedown.html . && mv one_page_resume_pagedown.html index.html
          git add long_form_cv/long_form_cv_vitae*
          git add one_page_resume/one_page_resume_pagedown*
          git add index.html
          git commit -m 'Re-built my-document' || echo "No changes to commit"
          git push -f origin || echo "No changes to commit"
      
